language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: 4.4
script:
- npm run lint
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_f9d49e660b56_key -iv $encrypted_f9d49e660b56_iv
  -in .env.enc -out .env -d
env:
  global:
  - CF_APP=text-bot
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=skitid@us.ibm.com
  - CF_SPACE=dev
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/text-bot
  skip_cleanup: true
